/**
 * Datos de ejemplo — se usan cuando Firebase no está configurado.
 */
window.MUNI_DATA = {
  areas: window.MUNI_FIREBASE_SEED_AREAS || [],

  noticias: [
    {
      id: "n1",
      slug: "pavimentacion-avenida-libertad",
      areaSlug: "obras-publicas",
      titulo: "Avanzan los trabajos de pavimentación en Avenida Libertad",
      bajada: "Se completó el 60% de la obra que beneficiará a más de 800 familias del centro y barrios aledaños.",
      cuerpo: "<p>La Municipalidad informa que la pavimentación de Avenida Libertad —entre San Martín y Belgrano— alcanzó el 60% de avance. El proyecto incluye nueva cordón cuneta, señalización horizontal y mejoras en el sistema pluvial.</p><p>Los trabajos se realizan de lunes a viernes entre las 7 y las 17 hs. Se recomienda a los vecinos circular con precaución y respetar el desvío señalizado en calle Mitre.</p><p>La inversión forma parte del plan anual de infraestructura vial y se estima finalizar antes de invierno.</p>",
      imagen: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=900&h=560&fit=crop",
      ubicacion: "Av. Libertad, entre San Martín y Belgrano",
      barrio: "Centro",
      estadoObra: "en_curso",
      fechaPublicacion: "2026-05-18",
      destacada: true,
    },
    {
      id: "n2",
      slug: "campana-vacunacion-antigripal",
      areaSlug: "salud",
      titulo: "Campaña de vacunación antigripal en el Centro de Salud",
      bajada: "Grupos de riesgo pueden acercarse de lunes a viernes sin turno previo.",
      cuerpo: "<p>El área de Salud municipal reactivó la campaña de vacunación antigripal en el Centro de Salud Dr. Ramón Carrillo. Está dirigida a adultos mayores, embarazadas, personas con enfermedades crónicas y personal de salud.</p><p>Horario de atención: 8 a 12 hs. Se solicita llevar DNI y carnet de vacunas si lo tuviera.</p>",
      imagen: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=900&h=560&fit=crop",
      ubicacion: "Centro de Salud Dr. Ramón Carrillo",
      barrio: "Centro",
      estadoObra: "en_curso",
      fechaPublicacion: "2026-05-17",
      destacada: false,
    },
    {
      id: "n3",
      slug: "entrega-tablets-escuela-14",
      areaSlug: "educacion",
      titulo: "Entrega de tablets a la Escuela N° 14 para apoyo digital",
      bajada: "40 equipos reacondicionados permitirán reforzar la alfabetización digital en primaria.",
      cuerpo: "<p>Educación municipal entregó 40 tablets reacondicionadas a la Escuela N° 14, en el marco del programa «Aula Conectada». Los dispositivos serán utilizados en talleres de lectura, matemática y programación inicial.</p><p>La escuela recibió además capacitación docente para el uso pedagógico de las herramientas.</p>",
      imagen: "https://images.unsplash.com/photo-1503676260728-1c00da094a41?w=900&h=560&fit=crop",
      ubicacion: "Escuela N° 14",
      barrio: "Barrio Sur",
      estadoObra: "finalizado",
      fechaPublicacion: "2026-05-16",
      destacada: false,
    },
    {
      id: "n3b",
      slug: "campana-antirrabica-zoonosis",
      areaSlug: "zoonosis",
      titulo: "Campaña antirrábica gratuita en barrios",
      bajada: "Zoonosis municipal vacunará perros y gatos durante mayo en puntos fijos y recorridos barriales.",
      cuerpo: "<p>El área de Zoonosis realiza una campaña antirrábica gratuita en distintos barrios de la ciudad. Los vecinos pueden acercarse con sus mascotas al puesto móvil sin turno previo.</p><p>Se recuerda la importancia de la tenencia responsable y el uso de correa en la vía pública.</p>",
      imagen: "https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=900&h=560&fit=crop",
      ubicacion: "Puntos móviles (itinerante)",
      barrio: "Varios",
      estadoObra: "en_curso",
      fechaPublicacion: "2026-05-16",
      destacada: false,
    },
    {
      id: "n4",
      slug: "circuito-cascada-municipal",
      areaSlug: "turismo",
      titulo: "Nuevo circuito guiado por la Cascada Municipal",
      bajada: "Visitas los sábados y domingos con salida desde la Oficina de Turismo.",
      cuerpo: "<p>Turismo presenta un circuito guiado de 90 minutos por senderos y miradores de la Cascada Municipal. Incluye interpretación ambiental y paradas fotográficas.</p><p>Salidas: sábados y domingos a las 10 y 16 hs. Punto de encuentro: Oficina de Turismo (Av. San Martín 120). Cupo limitado, inscripción gratuita.</p>",
      imagen: "https://images.unsplash.com/photo-1432407692361-2710a0c0b4a0?w=900&h=560&fit=crop",
      ubicacion: "Cascada Municipal",
      barrio: "Reserva Natural",
      estadoObra: "en_curso",
      fechaPublicacion: "2026-05-15",
      destacada: false,
    },
    {
      id: "n5",
      slug: "torneo-futbol-barrial-primavera",
      areaSlug: "deportes",
      titulo: "Arranca el Torneo de Fútbol Barrial «Primavera 2026»",
      bajada: "16 equipos de la ciudad compiten en categorías Sub-15 y Libre en el Polideportivo Municipal.",
      cuerpo: "<p>Deportes municipal da inicio al torneo barrial con 16 equipos inscriptos. Los partidos se jugarán los miércoles y sábados en el Polideportivo Municipal.</p><p>Fixture disponible en la secretaría de Deportes y en este portal. Entrada libre y gratuita para hinchadas locales.</p>",
      imagen: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=900&h=560&fit=crop",
      ubicacion: "Polideportivo Municipal",
      barrio: "Barrio Norte",
      estadoObra: "en_curso",
      fechaPublicacion: "2026-05-14",
      destacada: false,
    },
    {
      id: "n6",
      slug: "plantacion-arboles-plaza-san-martin",
      areaSlug: "ambiente",
      titulo: "Plantación de 50 árboles nativos en Plaza San Martín",
      bajada: "Voluntarios vecinales sumaron esfuerzos con el equipo de Espacios Verdes.",
      cuerpo: "<p>Medio Ambiente concretó la plantación de 50 ejemplares nativos en Plaza San Martín. Participaron estudiantes secundarios y referentes barriales en una jornada de concientización sobre especies autóctonas.</p><p>Se programó riego y seguimiento durante los próximos 12 meses.</p>",
      imagen: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=900&h=560&fit=crop",
      ubicacion: "Plaza San Martín",
      barrio: "Centro",
      estadoObra: "finalizado",
      fechaPublicacion: "2026-05-13",
      destacada: false,
    },
    {
      id: "n7",
      slug: "alumbrado-led-barrio-oeste",
      areaSlug: "obras-publicas",
      titulo: "Renovación de alumbrado LED en Barrio Oeste",
      bajada: "120 luminarias nuevas mejoran la seguridad vial en calles principales.",
      cuerpo: "<p>Obras Públicas avanza con el reemplazo de luminarias en Barrio Oeste. El proyecto contempla 120 artefactos LED de bajo consumo en un radio de 8 cuadras.</p><p>Estimación de finalización: fines de junio.</p>",
      imagen: "https://images.unsplash.com/photo-1513828583688-c52646db42da?w=900&h=560&fit=crop",
      ubicacion: "Barrio Oeste",
      barrio: "Barrio Oeste",
      estadoObra: "en_curso",
      fechaPublicacion: "2026-05-12",
      destacada: false,
    },
    {
      id: "n8",
      slug: "taller-primeros-auxilios-barrios",
      areaSlug: "salud",
      titulo: "Taller gratuito de primeros auxilios en barrios",
      bajada: "Capacitaciones itinerantes durante mayo en cinco barrios de la ciudad.",
      cuerpo: "<p>Salud municipal ofrece talleres de primeros auxilios RCP y maniobras básicas. Cronograma disponible en el área de Salud. Duración: 2 horas. Certificado de asistencia incluido.</p>",
      imagen: "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=900&h=560&fit=crop",
      ubicacion: "Centros barriales (itinerante)",
      barrio: "Varios",
      estadoObra: "planificado",
      fechaPublicacion: "2026-05-11",
      destacada: false,
    },
  ],

  eventosFlyers: [
    {
      id: "demo-ev1",
      areaSlug: "turismo",
      titulo: "Circuito Cascada Municipal",
      imagenUrl: "https://images.unsplash.com/photo-1432407692361-2710a0c0b4a0?w=540&h=960&fit=crop",
      fechaEvento: "2026-06-14",
      estadoPublicacion: "publicado",
    },
    {
      id: "demo-ev2",
      areaSlug: "deportes",
      titulo: "Torneo barrial de fútbol",
      imagenUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=540&h=960&fit=crop",
      fechaEvento: "2026-06-21",
      estadoPublicacion: "publicado",
    },
  ],
};
